export const BAR = "INTERACTIVE/BAR";
export const BUTTON_MORE = "INTERACTIVE/BUTTON_MORE";
export const PRELOADER = "INTERACTIVE/PRELOADER";
export const OPEN_INFO_TOOL_TIP_POPUP = "INTERACTIVE/OPEN_INFO_TOOL_TIP_POPUP";
export const NOTHING_FOUND = "INTERACTIVE/NOTHING_FOUND";